name: PHP CI

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PHP syntax
        run: php -l index.php

      - name: Build Docker image
        run: docker build -t php-cicd-demo .